version: '3.8'
services:
  cache:
    image: redis:latest
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: redis-server --save 10 1 --loglevel warning --requirepass Nikita@SuperBoss
    volumes:
      - cache:/data
volumes:
  cache:
    driver: local